version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: springboot_db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exercise_db
    ports: 
      - "5433:5432"
    volumes:
      - volume_postgres:/var/lib/postgresql/data
      - ./postgres_service/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 3200:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - net

volumes:
  volume_postgres:
    name: vpg
  volume_pgadmin:
    name: vpga

networks:
  net: